// src/App.tsx
import { useState } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom'
import { Database, Settings, BarChart3, Servers } from 'lucide-react'

// Pages
import Dashboard from './pages/Dashboard'
import Orders from './pages/Orders'
import Instances from './pages/Instances'
import Usage from './pages/Usage'
import Settings from './pages/Settings'

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5,
      gcTime: 1000 * 60 * 10,
      retry: 1,
    },
  },
})

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen bg-gray-50">
      {/* Sidebar */}
      <nav className="w-64 bg-white shadow-sm border-r border-gray-200">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <Database className="w-8 h-8 text-blue-600" />
            <div>
              <h1 className="text-xl font-bold text-gray-900">DB Backoffice</h1>
              <p className="text-xs text-gray-500">Management System</p>
            </div>
          </div>
        </div>

        <ul className="p-4 space-y-2">
          <li>
            <Link
              to="/"
              className="flex items-center gap-3 px-4 py-2.5 text-gray-700 hover:bg-blue-50 rounded-lg transition"
            >
              <BarChart3 className="w-5 h-5" />
              Dashboard
            </Link>
          </li>
          <li>
            <Link
              to="/orders"
              className="flex items-center gap-3 px-4 py-2.5 text-gray-700 hover:bg-blue-50 rounded-lg transition"
            >
              <Database className="w-5 h-5" />
              Orders
            </Link>
          </li>
          <li>
            <Link
              to="/instances"
              className="flex items-center gap-3 px-4 py-2.5 text-gray-700 hover:bg-blue-50 rounded-lg transition"
            >
              <Servers className="w-5 h-5" />
              Instances
            </Link>
          </li>
          <li>
            <Link
              to="/usage"
              className="flex items-center gap-3 px-4 py-2.5 text-gray-700 hover:bg-blue-50 rounded-lg transition"
            >
              <BarChart3 className="w-5 h-5" />
              Usage & Analytics
            </Link>
          </li>
          <li>
            <Link
              to="/settings"
              className="flex items-center gap-3 px-4 py-2.5 text-gray-700 hover:bg-blue-50 rounded-lg transition"
            >
              <Settings className="w-5 h-5" />
              Settings
            </Link>
          </li>
        </ul>
      </nav>

      {/* Main Content */}
      <main className="flex-1 overflow-auto">{children}</main>
    </div>
  )
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Router>
        <Routes>
          <Route
            path="/"
            element={
              <Layout>
                <Dashboard />
              </Layout>
            }
          />
          <Route
            path="/orders"
            element={
              <Layout>
                <Orders />
              </Layout>
            }
          />
          <Route
            path="/instances"
            element={
              <Layout>
                <Instances />
              </Layout>
            }
          />
          <Route
            path="/usage"
            element={
              <Layout>
                <Usage />
              </Layout>
            }
          />
          <Route
            path="/settings"
            element={
              <Layout>
                <Settings />
              </Layout>
            }
          />
        </Routes>
      </Router>
    </QueryClientProvider>
  )
}

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import Router from 'svelte-spa-router'
  import { Database, Settings as SettingsIcon, BarChart3, Server } from '@lucide/svelte'
  import './app.css'

  // Pages (lazy load)
  import Dashboard from './routes/Dashboard.svelte'
  import Orders from './routes/Orders.svelte'
  import Instances from './routes/Instances.svelte'
  import Usage from './routes/Usage.svelte'
  import Settings from './routes/Settings.svelte'

  let currentPath = '/'

  const routes = {
    '/': Dashboard,
    '/orders': Orders,
    '/instances': Instances,
    '/usage': Usage,
    '/settings': Settings,
  }

  const navItems = [
    { href: '/', label: 'Dashboard', icon: BarChart3 },
    { href: '/orders', label: 'Orders', icon: Database },
    { href: '/instances', label: 'Instances', icon: Server },
    { href: '/usage', label: 'Usage & Analytics', icon: BarChart3 },
    { href: '/settings', label: 'Settings', icon: SettingsIcon },
  ]

  function isActive(path: string): boolean {
    return currentPath === path
  }
</script>

<div class="flex h-screen bg-gray-50">
  <!-- Sidebar -->
  <nav class="w-64 bg-white shadow-sm border-r border-gray-200">
    <div class="p-6 border-b border-gray-200">
      <div class="flex items-center gap-3">
        <Database class="w-8 h-8 text-blue-600" />
        <div>
          <h1 class="text-xl font-bold text-gray-900">DB Backoffice</h1>
          <p class="text-xs text-gray-500">Management System</p>
        </div>
      </div>
    </div>

    <ul class="p-4 space-y-2">
      {#each navItems as item}
        <li>
          <a
            href={item.href}
            class="flex items-center gap-3 px-4 py-2.5 rounded-lg transition"
            class:bg-blue-50={isActive(item.href)}
            class:text-blue-700={isActive(item.href)}
            class:text-gray-700={!isActive(item.href)}
            class:hover:bg-blue-50={!isActive(item.href)}
          >
            <svelte:component this={item.icon} class="w-5 h-5" />
            {item.label}
          </a>
        </li>
      {/each}
    </ul>
  </nav>

  <!-- Main Content -->
  <main class="flex-1 overflow-auto">
    <Router {routes} on:routeLoaded={(e) => (currentPath = e.detail.route)} />
  </main>
</div>
